# Generated by Django 5.2.6 on 2026-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('fonction', models.CharField(blank=True, help_text='Ex. Mariée, Directeur, Client…', max_length=150, verbose_name='Fonction / qualité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/', verbose_name='Photo')),
                ('avis', models.TextField(verbose_name='Avis / témoignage')),
                ('note', models.PositiveSmallIntegerField(default=5, help_text='Note de 1 à 5', verbose_name='Note')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('publie_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
