# Generated by Django 5.2.6 on 2026-07-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénom(s)')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=20, null=True, verbose_name='Sexe')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('membre', 'Membre'), ('client', 'Client')], default='membre', max_length=20, verbose_name='Rôle')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse')),
                ('fonction_poste', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction / poste')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts/', verbose_name='Photo')),
                ('reseau_social_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('reseau_social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('reseau_social_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('reseau_social_youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
