# Generated by Django 5.2.6 on 2026-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'ordering': ['ordre', 'prenoms', 'nom'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='customeruser',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text='0 = premier à l’affichage, puis 1, 2…', verbose_name='Ordre'),
        ),
    ]
