# Generated by Django 5.2.6 on 2026-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('icone', models.CharField(default='la-graduation-cap', help_text='Ex: la-camera-retro', max_length=50, verbose_name='Icône Line Awesome')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée')),
                ('niveau', models.CharField(max_length=100, verbose_name='Niveau')),
                ('description', models.TextField(verbose_name='Description')),
                ('points', models.JSONField(blank=True, default=list, verbose_name='Points clés')),
                ('image', models.CharField(blank=True, help_text='Ex: front/assets/img/gallery/1.jpg', max_length=255, verbose_name='Image (chemin static)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('confirme', 'Confirmé')], max_length=20, verbose_name='Niveau')),
                ('message', models.TextField(blank=True, verbose_name='Message / objectifs')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formations', models.ManyToManyField(related_name='inscriptions', to='formation.formation', verbose_name='Formations')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
