# Generated by Django 5.2.6 on 2026-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_seed_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/images/', verbose_name='Image de la formation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
