# Generated by Django 5.2.6 on 2026-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(help_text='Ex. : Réseaux sociaux, Reels, Promo', max_length=100, verbose_name='Catégorie')),
                ('titre', models.CharField(help_text='Titre affiché sur le visuel. Ex. : Teaser de mariage', max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, help_text='Visuel branding. Si vide, l’image de secours est utilisée.', upload_to='medias/branding/', verbose_name='Image')),
                ('image_statique', models.CharField(blank=True, help_text='Ex. front/assets/img/gallery/1.jpg', max_length=255, verbose_name='Image static (secours)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='0 = premier visuel, puis 1, 2…', verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer ce visuel sur le site.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'branding',
                'verbose_name_plural': 'brandings',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(help_text='Ex. : Mariage, Portrait, Événement', max_length=100, verbose_name='Catégorie')),
                ('titre', models.CharField(help_text='Titre affiché sur la photo. Ex. : Cérémonie de mariage', max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, help_text='Photo de la galerie. Si vide, l’image de secours est utilisée.', upload_to='medias/photographies/', verbose_name='Image')),
                ('image_statique', models.CharField(blank=True, help_text='Ex. front/assets/img/gallery/1.jpg', max_length=255, verbose_name='Image static (secours)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='0 = première photo, puis 1, 2…', verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer cette photo sur le site.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'photographie',
                'verbose_name_plural': 'photographies',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(help_text='Ex. : Mariage, Cérémonie, Corporate', max_length=100, verbose_name='Catégorie')),
                ('titre', models.CharField(help_text='Titre affiché sous la vidéo. Ex. : Film de mariage', max_length=200, verbose_name='Titre')),
                ('video', models.FileField(blank=True, help_text='Fichier MP4 (ou similaire). Si vide, la vidéo de secours est utilisée.', upload_to='medias/videos/', verbose_name='Fichier vidéo')),
                ('video_statique', models.CharField(blank=True, help_text='Ex. front/assets/video/hero-video.mp4', max_length=255, verbose_name='Vidéo static (secours)')),
                ('poster', models.ImageField(blank=True, help_text='Image affichée avant la lecture de la vidéo.', upload_to='medias/videos/posters/', verbose_name='Image de couverture (poster)')),
                ('poster_statique', models.CharField(blank=True, help_text='Ex. front/assets/img/gallery/1.jpg', max_length=255, verbose_name='Poster static (secours)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='0 = première vidéo, puis 1, 2…', verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer cette vidéo sur le site.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vidéo',
                'verbose_name_plural': 'vidéos',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
