# Generated by Django 5.2.6 on 2026-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_seed_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(help_text='Ex. : Site vitrine, E-commerce, Landing page', max_length=100, verbose_name='Catégorie')),
                ('titre', models.CharField(help_text='Titre du projet. Ex. : Site web restaurant', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Courte description du projet web.', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Aperçu du projet. Si vide, l’image de secours est utilisée.', upload_to='medias/web_design/', verbose_name='Image')),
                ('image_statique', models.CharField(blank=True, help_text='Ex. front/assets/img/gallery/1.jpg', max_length=255, verbose_name='Image static (secours)')),
                ('url_projet', models.URLField(blank=True, help_text='Lien vers le site en ligne (optionnel).', verbose_name='URL du projet')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='0 = premier projet, puis 1, 2…', verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer ce projet sur le site.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'web design',
                'verbose_name_plural': 'web designs',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
