# Generated by Django 5.2.6 on 2026-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_webdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographie',
            name='categorie',
            field=models.CharField(db_index=True, help_text='Ex. : Mariage, Portrait, Événement. Plusieurs photos peuvent partager la même catégorie.', max_length=100, verbose_name='Catégorie'),
        ),
    ]
