# Generated by Django 5.2.6 on 2026-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('lieu', models.CharField(max_length=200, verbose_name="Lieu de l'événement")),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('prestations', models.JSONField(blank=True, default=list, verbose_name='Prestations')),
                ('type_evenement', models.CharField(choices=[('mariage', 'Mariage'), ('portrait', 'Portrait / Studio'), ('ceremonie', 'Cérémonie'), ('entreprise', "Événement d'entreprise"), ('anniversaire', 'Anniversaire / Fête'), ('autre', 'Autre')], max_length=30, verbose_name="Type d'événement")),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_analyse', 'En analyse'), ('traitee', 'Traitée'), ('refusee', 'Refusée')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('retour', models.TextField(blank=True, help_text='Message envoyé au client après analyse de la demande.', verbose_name='Retour au client')),
                ('retour_envoye_at', models.DateTimeField(blank=True, null=True, verbose_name='Retour envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
