# Generated by Django 5.2.6 on 2026-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtitre', models.CharField(max_length=200, verbose_name='Surtitre')),
                ('ligne_1_avant', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (avant accent)')),
                ('ligne_1_accent', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (mot accentué)')),
                ('ligne_1_apres', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (après accent)')),
                ('ligne_2_avant', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (avant accent)')),
                ('ligne_2_accent', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (mot accentué)')),
                ('ligne_2_apres', models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (après accent)')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='sliders/', verbose_name='Image de fond')),
                ('image_statique', models.CharField(blank=True, help_text='Ex. front/assets/img/slider/dream_slider_1.jpeg — utilisé si aucune image uploadée.', max_length=255, verbose_name='Image static (secours)')),
                ('bouton_texte', models.CharField(default='Nos Services', max_length=80, verbose_name='Texte du bouton')),
                ('bouton_lien', models.CharField(default='/photographie/', help_text='Chemin relatif, ex. /photographie/ ou /contact/', max_length=255, verbose_name='Lien du bouton')),
                ('overlay', models.CharField(choices=[('overlay-2', 'Overlay 2'), ('overlay-4', 'Overlay 4')], default='overlay-4', max_length=20, verbose_name='Overlay')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
