# Generated by Django 5.2.6 on 2026-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_seed_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='bouton_lien',
            field=models.CharField(default='/photographie/', help_text='Page ouverte au clic, ex. /photographie/ ou /contact/', max_length=255, verbose_name='Lien du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bouton_texte',
            field=models.CharField(default='Nos Services', help_text='Ex. Nos Services', max_length=80, verbose_name='Texte du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(help_text='Court paragraphe sous le grand titre.', verbose_name='Texte de présentation'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, help_text='Grande image en arrière-plan du slide.', upload_to='sliders/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_accent',
            field=models.CharField(blank=True, help_text='Ce texte apparaît en couleur / en évidence.', max_length=150, verbose_name='Mot mis en valeur'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_apres',
            field=models.CharField(blank=True, help_text='Partie normale après le mot mis en valeur.', max_length=150, verbose_name='Texte après'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_avant',
            field=models.CharField(blank=True, help_text='Partie normale avant le mot mis en valeur.', max_length=150, verbose_name='Texte avant'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_accent',
            field=models.CharField(blank=True, help_text='Ce texte apparaît en couleur / en évidence.', max_length=150, verbose_name='Mot mis en valeur'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_apres',
            field=models.CharField(blank=True, help_text='Partie normale après le mot mis en valeur.', max_length=150, verbose_name='Texte après'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_avant',
            field=models.CharField(blank=True, help_text='Partie normale avant le mot mis en valeur.', max_length=150, verbose_name='Texte avant'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text='0 = premier slide, puis 1, 2…', verbose_name='Ordre d’affichage'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='overlay',
            field=models.CharField(choices=[('overlay-2', 'Assombrissement léger'), ('overlay-4', 'Assombrissement fort')], default='overlay-4', help_text='Rend le texte plus lisible sur la photo.', max_length=20, verbose_name='Assombrissement de l’image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='surtitre',
            field=models.CharField(help_text='Petite phrase au-dessus du grand titre.', max_length=200, verbose_name='Petit titre (au-dessus)'),
        ),
    ]
