# Generated by Django 5.2.6 on 2026-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_clearer_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='bouton_lien',
            field=models.CharField(default='/photographie/', help_text='Chemin relatif, ex. /photographie/ ou /contact/', max_length=255, verbose_name='Lien du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bouton_texte',
            field=models.CharField(default='Nos Services', max_length=80, verbose_name='Texte du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='sliders/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_accent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (mot accentué)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_apres',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (après accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_avant',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 1 (avant accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_accent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (mot accentué)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_apres',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (après accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_avant',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre ligne 2 (avant accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='overlay',
            field=models.CharField(choices=[('overlay-2', 'Overlay 2'), ('overlay-4', 'Overlay 4')], default='overlay-4', max_length=20, verbose_name='Overlay'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='surtitre',
            field=models.CharField(max_length=200, verbose_name='Surtitre'),
        ),
    ]
