# Generated by Django 5.2.6 on 2026-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_revert_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='bouton_lien',
            field=models.CharField(default='/photographie/', help_text='Page ouverte au clic. Ex. : /photographie/ ou /contact/', max_length=255, verbose_name='Lien du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bouton_texte',
            field=models.CharField(default='Nos Services', help_text='Libellé du bouton. Ex. : Nos Services', max_length=80, verbose_name='Texte du bouton'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(help_text='Court paragraphe affiché sous le titre.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo en arrière-plan du slide. Si vide, l’image de secours est utilisée.', upload_to='sliders/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décochez pour masquer ce slide sur le site.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_accent',
            field=models.CharField(blank=True, help_text='Mot ou expression mis en évidence (couleur). Ex. : Ensemble ou Dream Consulting Com', max_length=150, verbose_name='Titre ligne 1 (mot accentué)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_apres',
            field=models.CharField(blank=True, help_text='Texte normal après le mot mis en valeur. Laissez vide si inutile.', max_length=150, verbose_name='Titre ligne 1 (après accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_1_avant',
            field=models.CharField(blank=True, help_text='Texte normal avant le mot mis en valeur. Ex. : Sublimons', max_length=150, verbose_name='Titre ligne 1 (avant accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_accent',
            field=models.CharField(blank=True, help_text='Mot mis en évidence sur la 2ᵉ ligne. Ex. : Inoubliables', max_length=150, verbose_name='Titre ligne 2 (mot accentué)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_apres',
            field=models.CharField(blank=True, help_text='Fin de la 2ᵉ ligne. Ex. : pour Toujours', max_length=150, verbose_name='Titre ligne 2 (après accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ligne_2_avant',
            field=models.CharField(blank=True, help_text='Début de la 2ᵉ ligne du titre. Ex. : Photographie & Événementiel', max_length=150, verbose_name='Titre ligne 2 (avant accent)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text='Position dans le carrousel : 0 = premier, puis 1, 2…', verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='overlay',
            field=models.CharField(choices=[('overlay-2', 'Overlay 2'), ('overlay-4', 'Overlay 4')], default='overlay-4', help_text='Assombrissement de l’image pour mieux lire le texte (2 = léger, 4 = plus fort).', max_length=20, verbose_name='Overlay'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='surtitre',
            field=models.CharField(help_text="Petite phrase au-dessus du grand titre. Ex. : Capturez l'instant, vivez l'émotion !", max_length=200, verbose_name='Surtitre'),
        ),
    ]
