# Generated by Django 5.2.6 on 2026-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('sujet', models.CharField(help_text='Ex. : mariage, portrait, événement…', max_length=200, verbose_name='Sujet / type de projet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('reponse', models.TextField(blank=True, help_text='Message envoyé au client depuis le back-office.', verbose_name='Réponse au client')),
                ('reponse_envoyee_at', models.DateTimeField(blank=True, null=True, verbose_name='Réponse envoyée le')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
