# Generated by Django 5.2.6 on 2026-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAccordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'panneau à propos',
                'verbose_name_plural': 'panneaux à propos',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Capturons Aujourd'hui", max_length=200, verbose_name='Titre (ligne 1)')),
                ('sous_titre_debut', models.CharField(default='Vos Plus', max_length=100, verbose_name='Sous-titre (avant le mot mis en avant)')),
                ('mot_accent', models.CharField(default='Beaux', help_text='Affiché dans un <span> sur le site.', max_length=50, verbose_name='Mot mis en avant')),
                ('sous_titre_fin', models.CharField(default='Souvenirs', max_length=100, verbose_name='Sous-titre (après le mot mis en avant)')),
                ('introduction', models.TextField(default='Nous immortalisons vos émotions, sublimons vos événements et créons des souvenirs inoubliables pour toute une vie.', verbose_name='Introduction')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Image')),
                ('bouton_texte', models.CharField(default='À propos', max_length=50, verbose_name='Texte du bouton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'section à propos',
                'verbose_name_plural': 'section à propos',
            },
        ),
    ]
